import createTheme from 'styled-components-theme';
import * as tinycolor from "tinycolor2";
const accent = '#30AFFF';

export const colors = {
    accent:accent,
    accent_secondary: tinycolor(accent).spin(19).darken(4).toString(),
    icon_default:'#fff',
    panel_background:'#111A29',
    flyout_background: '#111A29',
    margin1:'8px',
    margin2:'16px',
    separator_color: "#5D7590",
    rightPropSize:"48px",
    prop_height:'24px',
    flyout_shadow: '0 0 4px 1px rgba(0, 0, 0, 0.5)',
    dropdown_shadow: '0px 1px 1px 0px rgba(0,0,0,0.5)',
    input_shadow: '0 0 8px rgba(0, 0, 0, 0.1)',
    text:'#d7d7d7',
    text_active:accent,
    text_inactive:'#5D7590',
    text_color: '#ffffff',
    text_color_alternate: '#000',
    text_color_lowimportance:'#afacac',
    button_default: "#9b9a9b",
    stencil_background: "#fff",
    action_underline: "#fff",
    button_normal: "#1B2433",
    button_hover: "white",
    button_active: "#30AFFF",
    button_disabled:"#525252",
    workspace_background:'#172131',
    h1font: "400 25px 'ProximaNova-Regular', 'Roboto', sans-serif;",
    h2font: "bold 12px 'Roboto', sans-serif;",
    logo_font: "bold 15px 'Roboto', sans-serif;",
    menu_link_font: "bold 11px 'Proxima Nova', 'Roboto', sans-serif;",
    landing_h1font: "400 55px 'Roboto', sans-serif;",
    font_largeInput: "400 16px 'Roboto', sans-serif;",
    default_font: "400 12px 'Roboto', sans-serif;",
    link_font: "400 10px 'Roboto', sans-serif;",
    tab_font: "400 10px 'Roboto', sans-serif;",
    input_font: "400 12px 'Roboto', sans-serif;",
    input_placeholder_color: '#5D7590',
    prop_font: "400 9px 'Roboto', sans-serif;",
    button_caption_font: "400 9px 'Roboto', sans-serif;",
    prop_name_font: "400 12px 'Roboto', sans-serif;",
    leadFont: "bold 12pt 'Roboto', sans-serif;",
    link_padding: "8px",
    prop_sub_color: "#394859",
    input_background: "#1D2636",
    layer_page_background: "#212121",
    layer_selection_background: "#3498DB",
    layer_hover_background: "#2980B9",
    layer_artboard_background: "#172131",
    prop_container_background: "#172131",
    inactive_tab_button: '#212121',
    slider_progress: "#30AFFF",
    slider_track: "#242E3D"
}

const theme = createTheme(...Object.keys(colors));

export default theme